skippedCharacters = [" ", "\t", "\n", "\r"]
characterLiterals = ["n","r","t", "'", '"']

nonTerminals = {
  "S": 0,
  "program": 1,
  "def-list": 2,
  "def": 3,
  "var-def": 4,
  "var-list": 5,
  "id-list": 6,
  "id-list-cont": 7,
  "fun-def": 8,
  "param-list": 9,
  "var-def-list": 10,
  "stmt-list": 11,
  "stmt": 12,
  "stmt-assign": 13,
  "stmt-incr": 14,
  "stmt-decr": 15,
  "stmt-fun-call": 16,
  "fun-call": 17,
  "expr-list": 18,
  "expr-list-cont": 19,
  "stmt-if": 20,
  "else-if-list": 21,
  "else-stmt": 22,
  "stmt-loop": 23,
  "stmt-break": 24,
  "stmt-return": 25,
  "stmt-empty": 26,
  "expr":27,
  "expr-or": 28,
  "expr-and": 29,
  "expr-comp": 30,
  "op-comp": 31,
  "expr-rel": 32,
  "op-rel": 33,
  "expr-add": 34,
  "op-add": 35,
  "expr-mul": 36,
  "op-mul": 37,
  "expr-unary": 38,
  "op-unary": 39,
  "expr-primary":40,
  "array": 41,
  "lit": 42
}

separators = {
    "+": 1,
    ",": 2,
    "(": 3,
    ")": 4,
    "[": 5,
    "]": 6,
    "{": 7,
    "}": 8,
    "*": 9,
    "%": 10,
    "/": 11,
    #":": 12,
    ";": 13,
    "=": 14,
    #"+=": 15,
    #"-=": 16,
    #"*=": 17,
    #"/=": 18,
    #"%=": 19,
    "<": 20,
    ">": 21,
    "<=": 22,
    ">=": 23,
    "!=": 24,
    "==": 25,
    #"'": 26,
    #'"': 27,
    #"printi": 28,
    #"printc": 29,
    #"prints": 30,
    #"println": 31,
    #"new": 32,
    #"size": 33,
    #"add": 34,
    #"get": 35,
    #"set": 36
}

reservedWords = {
    #Keywords
    "return": 57,
    "break": 38,
    "-": 39,
    "and": 40,
    "or": 41,
    #"file": 42,
    #"field": 43,
    #"property": 44,
    #"get": 45,
    #"set": 46,
    #"receiver": 47,
    "var": 48,
    "inc": 49,
    "dec": 50,
    "if": 51,
    "else": 52,
    "elif": 53,
    "loop": 54,
    #"while": 55, 
    #"throw": 56,
    #"as": 58,
    #"is": 59,
    #"in": 60,
    "not": 61,
    #"f": 62,
}

alphabet = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z',
            'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z',
            '0', '1', '2', '3', '4', '5', '6', '7', '8', '9','_','\\',"'",'"']